require:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-sequel

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "app.rb"
    - "spec/system_spec.rb"

Metrics/ClassLength:
  Enabled: false

AllCops:
  NewCops: enable

Layout/TrailingEmptyLines:
  Enabled: false

Layout/InitialIndentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - views/*.erb
    - views/*/*.erb

Naming/FileName:
  Exclude:
    - "views/create-account.erb"
