Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config.ru'

AllCops:
  NewCops: enable

Layout/TrailingEmptyLines:
  Enabled: false

Layout/InitialIndentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - views/*.erb
    - views/*/*.erb
